name: deployment

on:
  push:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest   
    strategy:
      matrix:
        node-version: [20.x]   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


      - name: Create .env.production file
        run: |
          echo "REACT_APP_KAKAO_REST_API_KEY=${{ secrets.REACT_APP_KAKAO_REST_API_KEY }}" >> .env.production
          echo "REACT_APP_KAKAO_JS_KEY=${{ secrets.REACT_APP_KAKAO_JS_KEY }}" >> .env.production
          echo "REACT_APP_EDGE_SERVICE_URL=${{ secrets.REACT_APP_EDGE_SERVICE_URL }}" >> .env.production

          echo "REACT_APP_DEV_AWS_S3_BUCKET=${{ secrets.REACT_APP_DEV_AWS_S3_BUCKET }}" >> .env.production
          echo "REACT_APP_AWS_ACCESS_KEY_ID=${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}" >> .env.production
          echo "REACT_APP_AWS_SECRET_ACCESS_KEY=${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}" >> .env.production
          echo "REACT_APP_AWS_REGION=${{ secrets.REACT_APP_AWS_REGION }}" >> .env.production

      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI="false" npm run build

      - name: 빌드파일위치
        run: pwd

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REACT_APP_AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./build s3://${{ secrets.REACT_APP_DEV_AWS_S3_BUCKET }}/prod/ --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DEV_AWS_DISTRIBUTION_ID}} --paths "/*"

